---
title: 02_assignment
layout: default
---

# **Laser cut a box with finger joints**

In this fourth assignment, the task was to laser-cut wooden pieces and build a 6-side parametric box. To assemble the parts that create the box, finger joints were designed at the edges of the wooden pieces. The whole point of the finger joints is to hold the box together instead of glue, screws, etc. 


## ** Fusion360 design** 

### **Bottom side of the parametric box**

The parametric box was designed using Fusion360 (Figure 1, blue panel), and the size of the box was top decided to be 45mm x 45mm x 45mm, making the box a perfect square. Initially, I designed the bottom part of the box. I used the center rectangle function and selected the origin point as my center in the XY plane. Then, it was time for the finger joints, and the first step was to mark out the cuts. I created four identical  rectangles along the north and west inward side of the sketch, measuring 6mm x 3mm. After that, I used the mirror command to mirror the rectangles to the south and east sides of the sketch. As mentioned above, the dimensions of the 2D bottom part were 45mm x 45mm. After designing the bottom part, I used the extrude command to give ‘’height’’ to the bottom sketch by 3mm.

![parametric box ](https://github.com/vtryfos/vtryfos.github.io/assets/143755086/9b5b6095-5d7a-4a60-9870-5523f723a114)
Figure 1: Shows the design of the bottom (blue shaded area) and the side panel (gray area) of the parametric box in Fusion360.


### **One of the sides of the parametric box**





